// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Role struct {
	ID        int64
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Token struct {
	ID        int64
	Token     string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserRole struct {
	ID        int64
	RoleID    int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
