// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rolequeries.sql

package database

import (
	"context"
)

const getRoleByName = `-- name: GetRoleByName :one
SELECT id FROM roles
WHERE role = ?
`

func (q *Queries) GetRoleByName(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, role)
	var id int64
	err := row.Scan(&id)
	return id, err
}
