// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokenqueries.sql

package database

import (
	"context"
	"time"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (
  token, user_id, expires_at
) VALUES (
  ?, ?, ?
)
RETURNING id, token, user_id, expires_at, created_at, updated_at
`

type CreateTokenParams struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTokenById = `-- name: DeleteTokenById :exec
DELETE FROM tokens
WHERE id = ?
`

func (q *Queries) DeleteTokenById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTokenById, id)
	return err
}

const deleteTokenByUserId = `-- name: DeleteTokenByUserId :exec
DELETE FROM tokens
WHERE user_id = ?
`

func (q *Queries) DeleteTokenByUserId(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTokenByUserId, userID)
	return err
}

const getTokenByUserId = `-- name: GetTokenByUserId :one
SELECT id, token, user_id, expires_at, created_at, updated_at FROM tokens
WHERE user_id = ?
`

func (q *Queries) GetTokenByUserId(ctx context.Context, userID int64) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByUserId, userID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFromToken = `-- name: GetUserFromToken :one
SELECT users.id, users.username, users.email, users.password_hash, users.created_at, users.updated_at FROM users
INNER JOIN tokens ON users.id = tokens.user_id
WHERE tokens.token = ? LIMIT 1
`

func (q *Queries) GetUserFromToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
