// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: userrolequeries.sql

package database

import (
	"context"
)

const createUserRole = `-- name: CreateUserRole :one
INSERT INTO user_roles (
    role_id, user_id
) VALUES (
  ?, ?
)
RETURNING id, role_id, user_id, created_at, updated_at
`

type CreateUserRoleParams struct {
	RoleID int64
	UserID int64
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, createUserRole, arg.RoleID, arg.UserID)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoleByUserId = `-- name: GetUserRoleByUserId :one
SELECT roles.id, roles.role, roles.created_at, roles.updated_at FROM roles
INNER JOIN user_roles ON roles.id = user_roles.role_id
WHERE user_roles.user_id = ? LIMIT 1
`

func (q *Queries) GetUserRoleByUserId(ctx context.Context, userID int64) (Role, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleByUserId, userID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
